version: '3.8'

services:
  web:
    build: .
    container_name: web-main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-main.rule=Host(`prod.pavan.today`)"
      - "traefik.http.routers.web-main.entrypoints=web"
      - "traefik.http.services.web-main.loadbalancer.server.port=3000"
    networks:
      - webnet
    restart: always

  traefik:
    image: traefik:v2.11
    container_name: traefik-main
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
