version: '3.8'

services:
  web:
    build: .
    container_name: web-${BRANCH_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${BRANCH_NAME}.rule=Host(`${BRANCH_NAME}.yourdomain.com`)"
      - "traefik.http.routers.${BRANCH_NAME}.entrypoints=web"
      - "traefik.http.services.${BRANCH_NAME}.loadbalancer.server.port=3000"
    networks:
      - webnet
    environment:
      - BRANCH_NAME=${BRANCH_NAME}
    restart: always

  traefik:
    image: traefik:v2.11
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
